-- V3__add_users_and_ownership.sql
-- Create users table, user ownership FK columns, and seed default admin user

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_user_username ON users (username);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS user_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_project_user_id ON projects (user_id);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS user_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_task_user_id ON tasks (user_id);

-- Seed default admin user (email: admin@vortiq.com / password: Password123!)
-- BCrypt hash for Password123!: $2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xD0m1bC.I.s36Cg2
INSERT INTO users (id, username, email, password, role, created_at)
VALUES (1, 'Admin', 'admin@vortiq.com', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xD0m1bC.I.s36Cg2', 'ROLE_ADMIN', CURRENT_TIMESTAMP)
ON CONFLICT (email) DO NOTHING;

-- Associate initial seeded projects and tasks with default admin user (id = 1)
UPDATE projects SET user_id = 1 WHERE user_id IS NULL;
UPDATE tasks SET user_id = 1 WHERE user_id IS NULL;
