-- V4__workspace_collaboration_platform.sql
-- Create workspaces, workspace_members tables, and update projects & tasks with collaboration FKs

ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(1000);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500);

CREATE TABLE IF NOT EXISTS workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    color_code VARCHAR(50) DEFAULT '#6366f1',
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workspace_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_workspace_name ON workspaces (name);
CREATE INDEX IF NOT EXISTS idx_workspace_owner ON workspaces (owner_id);

CREATE TABLE IF NOT EXISTS workspace_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ws_member_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_ws_member_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_ws_member UNIQUE (workspace_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_ws_member_workspace ON workspace_members (workspace_id);
CREATE INDEX IF NOT EXISTS idx_ws_member_user ON workspace_members (user_id);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS workspace_id BIGINT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_by_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_project_workspace_id ON projects (workspace_id);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS workspace_id BIGINT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_by_id BIGINT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assigned_to_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_task_workspace_id ON tasks (workspace_id);
CREATE INDEX IF NOT EXISTS idx_task_assigned_to ON tasks (assigned_to_id);

-- Seed default "VortiQ Studio Workspace" for existing admin user (id = 1)
INSERT INTO workspaces (id, name, description, color_code, owner_id, created_at)
VALUES (1, 'VortiQ Studio Workspace', 'Default enterprise workspace for team collaboration', '#6366f1', 1, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

INSERT INTO workspace_members (workspace_id, user_id, role, joined_at)
VALUES (1, 1, 'OWNER', CURRENT_TIMESTAMP)
ON CONFLICT (workspace_id, user_id) DO NOTHING;

-- Link existing projects and tasks to default workspace (id = 1)
UPDATE projects SET workspace_id = 1 WHERE workspace_id IS NULL;
UPDATE tasks SET workspace_id = 1 WHERE workspace_id IS NULL;
