-- V5__add_department_phone_and_messages.sql
-- Add department, phone, and workspace messaging schema

ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE users ALTER COLUMN avatar_url VARCHAR(1000);

CREATE TABLE IF NOT EXISTS workspace_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    sender_id BIGINT,
    sender_name VARCHAR(255) NOT NULL,
    sender_email VARCHAR(255),
    sender_avatar VARCHAR(1000),
    recipient_id BIGINT,
    recipient_name VARCHAR(255),
    content VARCHAR(3000) NOT NULL,
    message_type VARCHAR(50) DEFAULT 'GENERAL',
    task_id BIGINT,
    task_title VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_msg_workspace ON workspace_messages (workspace_id);
CREATE INDEX IF NOT EXISTS idx_msg_type ON workspace_messages (message_type);
CREATE INDEX IF NOT EXISTS idx_msg_recipient ON workspace_messages (recipient_id);

-- Initial Starter Message
INSERT INTO workspace_messages (workspace_id, sender_id, sender_name, sender_email, sender_avatar, content, message_type, task_id, task_title, created_at)
SELECT 1, 1, 'Sarah Chen', 'sarah@vortiq.com', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80', '⚠️ Inconvenience Report: Cloud database connection pool timed out during batch sync on Task #3. Resolved by optimizing timeout.', 'INCONVENIENCE', 3, 'Configure H2 Database Auto-schema', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM workspace_messages WHERE id = 1);
