-- V6__add_discussions_and_opinions_tables.sql
-- Create discussions and discussion_replies tables for team opinions and idea sharing

CREATE TABLE IF NOT EXISTS discussions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    author_id BIGINT,
    author_name VARCHAR(255) NOT NULL,
    author_email VARCHAR(255),
    author_avatar TEXT,
    author_department VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    category VARCHAR(50) DEFAULT 'OPINION',
    likes_count INT DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_disc_workspace ON discussions (workspace_id);
CREATE INDEX IF NOT EXISTS idx_disc_category ON discussions (category);

CREATE TABLE IF NOT EXISTS discussion_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discussion_id BIGINT NOT NULL,
    author_id BIGINT,
    author_name VARCHAR(255) NOT NULL,
    author_email VARCHAR(255),
    author_avatar TEXT,
    author_department VARCHAR(255),
    content VARCHAR(3000) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reply_discussion FOREIGN KEY (discussion_id) REFERENCES discussions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reply_discussion ON discussion_replies (discussion_id);

-- Seed Starter Opinions & Ideas
INSERT INTO discussions (workspace_id, author_id, author_name, author_email, author_avatar, author_department, title, content, category, likes_count, created_at)
SELECT 1, 1, 'Deepanshi Kaushal', 'deepanshi@vortiq.com', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=140&auto=format&fit=crop&q=80', 'Engineering & Development', 'Proposal: Transitioning API client architecture to Optimistic UI caching', 'Hey team! I propose we implement optimistic caching for Kanban column stage drags and Task status changes so the user gets instant zero-lag feedback before the server responds. What are your thoughts on this?', 'IDEA', 8, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM discussions WHERE id = 1);

INSERT INTO discussion_replies (discussion_id, author_id, author_name, author_email, author_avatar, author_department, content, created_at)
SELECT 1, 2, 'Sarah Chen', 'sarah@vortiq.com', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=140&auto=format&fit=crop&q=80', 'Product & Strategy', 'Totally agree Deepanshi! This makes the UI feel native and hyper-responsive, especially on mobile devices.', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM discussion_replies WHERE id = 1);

INSERT INTO discussions (workspace_id, author_id, author_name, author_email, author_avatar, author_department, title, content, category, likes_count, created_at)
SELECT 1, 3, 'Marcus Vance', 'marcus@vortiq.com', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=140&auto=format&fit=crop&q=80', 'Cloud Infrastructure & DevOps', 'Opinion: Friday afternoon deployments vs Monday morning releases', 'I believe we should restrict production releases after 3 PM on Fridays to prevent unexpected weekend incidents. Monday morning releases give the full team standard business hours to monitor telemetry. Thoughts?', 'OPINION', 12, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM discussions WHERE id = 2);
